const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const source = fs.readFileSync('tools/universe_ui/app.js', 'utf8');
const ctx = {}; vm.createContext(ctx);
vm.runInContext(source.slice(source.indexOf('function groupRagReviewCandidates('), source.indexOf('function renderMemory()')), ctx);
const candidate = (id, extra = {}) => ({project_id:'p',candidate_id:id,kind:'MEMORY',state:'REVIEW_REQUIRED',stage:'FAST_EXTRACT',summary:'같은 내용',provenance:{ref_digests:['evidence']},...extra});
const originals = [candidate('a'),candidate('b',{stage:'CONSOLIDATE'}),candidate('c',{summary:'새 내용'})];
const before = JSON.stringify(originals);
let groups = ctx.groupRagReviewCandidates(originals);
assert.equal(groups.length,2);assert.equal(groups[0].bucket,'pending');assert.equal(groups[0].items.length,2);assert.equal(groups[1].bucket,'pending');
assert.equal(JSON.stringify(originals),before);
groups = ctx.groupRagReviewCandidates([candidate('a'),candidate('b',{state:'CONFLICTED'}),candidate('c',{summary:'다른 것',state:'KEEP'})]);
assert.equal(groups[0].bucket,'pending');assert.ok(groups[0].reasons.includes('충돌 확인'));assert.equal(groups[0].items.length,2);
assert.equal(groups[1].bucket,'pending');
groups = ctx.groupRagReviewCandidates([candidate('a',{provenance:{}}),candidate('b',{kind:'IDEA',stage:'SYNTHESIZE',summary:'Idea candidate derived from 21 Memory candidates (839c598d8aeb80d3).'}),candidate('c',{state:'IGNORE'}),candidate('d',{state:'SUPERSEDED'})]);
assert.equal(groups.length,2);assert.ok(groups[0].reasons.includes('출처 확인 필요'));assert.ok(groups[1].reasons.includes('내용 보완 필요'));
groups = ctx.groupRagReviewCandidates([candidate('a',{summary:'ID'}),candidate('b',{summary:'id'}),candidate('c',{kind:'IDEA',summary:'ID'}),candidate('d',{project_id:'other',summary:'ID'})]);
assert.equal(groups.length,4);
console.log('PASS grouping, conflict priority, provenance, placeholders, archive, project/kind/case isolation, no mutation');

groups = ctx.groupRagReviewCandidates([candidate('current',{source_review:{bucket:'current'}}), candidate('future',{source_review:{bucket:'future'}}), candidate('old',{source_review:{bucket:'archive'}})]);
assert.equal(groups.length,2); assert.equal(groups[0].bucket,'current'); assert.equal(groups[1].bucket,'future');

const topicKnowledge = {kind:'USER_DECISION',topic:'메모 수집',applicability:'대화 수집 시'};
const records = [candidate('older',{summary:'유효한 사용자 결정',created_at:'2026-09-01',knowledge:topicKnowledge,source_review:{bucket:'current'}}),candidate('newer',{summary:'새로운 미검증 주장',created_at:'2026-09-14',knowledge:topicKnowledge}),candidate('copy',{summary:'유효한 사용자 결정',created_at:'2026-09-13',knowledge:topicKnowledge}),candidate('ignored',{knowledge:topicKnowledge,state:'IGNORE'})];
const originalRecords = JSON.stringify(records);
const topics = ctx.groupRagKnowledgeTopics(records, []);
assert.equal(topics.length,1);
assert.equal(topics[0].claims.length,2);
assert.equal(topics[0].entries.length,3);
assert.equal(topics[0].recent.item.candidate_id,'newer');
assert.equal(topics[0].verified[0].item.candidate_id,'older');
assert.equal(JSON.stringify(records),originalRecords);
assert.equal(ctx.groupRagKnowledgeTopics([records[0],{...records[0],project_id:'other'}],[]).length,2);
const combined = ctx.groupRagKnowledgeTopics([records[0]],[{memory_id:'m',project_id:'p',body:records[0].summary,knowledge:topicKnowledge}]);
assert.equal(combined.length,1); assert.equal(combined[0].claims.length,1);assert.equal(combined[0].claims[0].entries.length,2);
assert.equal(ctx.groupRagKnowledgeTopics([candidate('conflict',{knowledge:topicKnowledge,relations:[{relation:'CONFLICTS_WITH',candidate_id:'x'}]})],[])[0].hasConflict,true);
assert.equal(ctx.ragTopicFor(candidate('legacy',{summary:'RAG 메모 수집'})).inferred,true);
assert.equal(ctx.groupRagKnowledgeTopics([], [{memory_id:'ignored',retention:{decision:'IGNORE'}}]).length,0);
console.log('PASS topic grouping, cross-state duplicates, saved/candidate integration, recency versus validity, conflict retention, ignored memory exclusion');
