const fs=require("fs"),vm=require("vm"),assert=require("assert/strict");
const source=fs.readFileSync("tools/universe_ui/terminals.js","utf8");
const ctx={Date};vm.createContext(ctx);
vm.runInContext(source.slice(source.indexOf("function terminalInjectionProjection("),source.indexOf("function ensureTerminalSurface(")),ctx);
const project=(s,m)=>ctx.terminalInjectionProjection(s,m);
const session={session_anchor_ref:"anchor-a",host_turn_state:{latest_delivery:{message_id:"m1",phase:"AWAITING_START",submit_write_attempted_at_ms:Date.now()}}};
const message={message_id:"m1",kind:"INSTRUCTION",recipient_anchor_ref:"anchor-a",body_text:"<script>not markup</script>",lifecycle_state:"STARTED",lifecycle:{execution_phase:"DISPATCHED"}};
assert.equal(project(session,[message]).body,message.body_text,"Enter write must not clear body");
assert.equal(project(session,[{...message,recipient_anchor_ref:"anchor-b"}]).body,"","other session is excluded");
session.host_turn_state.latest_delivery.phase="PROMPT_SUBMITTED";
assert.equal(project(session,[message]).body,"");
assert.equal(project(session,[message]).status,"접수됨");
const claudeMessage={...message,message_id:"m2",lifecycle:{delivery_channel:"CLAUDE_CODE_CHANNEL",awaits_authoritative_reply:true,execution_phase:"DISPATCHED"}};
const claudeProjection=project(session,[claudeMessage]);
assert.equal(claudeProjection.statusCode,"AWAITING_AUTHORITATIVE_REPLY");
assert.equal(claudeProjection.body,message.body_text);
session.host_turn_state.latest_delivery.phase="SUBMIT_UNCONFIRMED";
assert.equal(project(session,[message]).body,message.body_text,"uncertainty retains original body");
assert.equal(project(session,[message]).status,"실패 · 확인 필요");
session.host_turn_state.latest_delivery.phase="AWAITING_START";
session.host_turn_state.latest_delivery.submit_write_attempted_at_ms=Date.now()-31000;
assert.equal(project(session,[message]).status,"제출 확인 지연");
assert.equal(project(session,[{...message,lifecycle_state:"REPLIED",lifecycle:{failed_at:"now"}}]).body,"");
assert.equal(project(session,[{...message,lifecycle_state:"DONE",lifecycle:{failed_at:"now"}}]).statusCode,"COMPLETED");
const nextMessage={...message,message_id:"m3",body_text:"next instruction",lifecycle_state:"QUEUED",lifecycle:{}};
assert.equal(project(session,[{...message,lifecycle_state:"DONE"},nextMessage]).messageId,"m3",
  "a completed stale receipt must not hide pending work");
const surface={injectionStatus:{},injectionBody:{},injectionDetail:{},injectionBox:{dataset:{}}};
ctx.paintTerminalInjectionBox(surface,project(session,[message]));
assert.equal(surface.injectionBody.value,message.body_text);
assert.equal(surface.injectionBody.innerHTML,undefined);
console.log("Injection box isolates sessions, preserves unacknowledged/failed messages and clears only confirmed input");

session.host_turn_state.latest_delivery.phase="NATIVE_QUEUED";
assert.equal(project(session,[message]).status,"CLI 큐 접수 · 실행 대기");
assert.equal(project(session,[message]).body,message.body_text);
session.host_turn_state.latest_delivery.phase="NATIVE_UNCONFIRMED";
assert.equal(project(session,[message]).status,"실패 · 확인 필요");
assert.equal(project(session,[message]).body,message.body_text);

const waiting={...claudeMessage,lifecycle:{...claudeMessage.lifecycle,quota_wait:{state:"WAITING_QUOTA",resets_at:1789458000}}};
assert.equal(project(session,[waiting]).statusCode,"WAITING_QUOTA");
assert.equal(project(session,[waiting]).body,waiting.body_text);
assert.equal(project(session,[{...waiting,lifecycle_state:"COMPLETED"}]).body,"");
